server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: akarsha-backend
  
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5435}/${PGDATABASE:akarsha}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.akarsha: DEBUG
    org.hibernate.SQL: INFO
